title: A mediocre title
author: Lackluster User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I hope this works! I acn't wait to have learned this stuff. 

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
